### ISSUE TITLE
[EPIC] Migrate UI to Gastby and update the UI

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/opendatahub.io#79]
This epic will serve as the root issue for the website UI update hackathon. This will only track UI changes and not content.

_This issue will link to more specific design issues_

### Shared Components
- [ ] content render card
- [ ] featured content card section
- [ ] stylized button
### Home Page
- [ ] navigation bar component
- [ ] header component
- [ ] competitive advantage component
- [ ] personas component
- [ ] case studies component
- [ ] community details component
- [ ] featured blogs component
- [ ] footer component
### Blog Page
- [ ] construct blog page with search / filtering by tag or by title
### Community Page
 - [ ] layouts of featured content
### Docs Page
- [ ] side navigation and docs-template
